### ISSUE TITLE
Reload Scorm 1.2 Player - course doesnt work run in reload

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-spoor#56]
When course is loaded into "Reload Scorm 1.2 Player" it doesnt work, console shows the `Uncaught SyntaxError: Unexpected identifier` usually pointing to the `index.html:1` or something similar to `VM485:1` - then it also presents following `this.cmi.suspend_data.cmivalue ="{"spoor":{"completion":"1000000000000000000000000000000000000","_isCourseComplete":false,"_isAssessmentPassed":false}}";` I presume this is because Reload evaluates strings and when it finds something like above then it breaks. I know that some of the LMS's were also infected with similar bug and I was forced to use a lot of escaping before storing any text data that could be interpreted as code.

**Comment by moloko** [comment]
Hi @LukaszGrela  - I've just tried to give this a go myself but seem unable to get the Reload player to install on Windows 7. It doesn't seem to have been updated since about 2004 (which is slightly worrying), doesn't seem to like Windows Aero (which it switched off) and the installer crashed twice before finally getting as far as the 'installing' section, whereupon it halts with no option to contine. Doesn't look like the world's most robust bit of software ;-)

One question - does it load the content up in a local web server? I find with some of these more out-of-date tools (e.g. the ADL SCORM 1.2 test suite) that they run content locally i.e. the course URL will start 'file://' - which is unlikely to work these days. Certainly I haven't been able to get anything like Adapt to launch in the ADL Test Suite.

Also anything that relies on Java seems inherently unstable these days too, unless you happen to have the version of Java that was around the last time it was updated. The ADL Test Suite also suffers from this - as well as not liking any newer version of Internet Explorer.

If Reload player is evaluating strings and the above suspend_data string is causing the error, then the Reload tool is the one at fault because that value *is* a completely valid value for cmi.suspend_data.
If you need to test your course for SCORM conformance then I'd suggest using SCORM Cloud.

**Comment by LukaszGrela** [comment]
Reload is Java based, but it runs a local server. I had no problems installing it on windows 7 (at least I dont recall it as it has been some time ago - and it works). ADL Test Suite is something else and I can't make it work with Win 7 - but again there is no relation. Of course that the JSON string is valid:) the problem is With Reload as it evaluates and then eval doesnt like it, I'm using SCORM Cloud however it is slower than having it run in Reload (uploading/updating tested courses).
