### ISSUE TITLE
LMS Suspend Data issue

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt-contrib-spoor#66]
Even if we complete the course, the suspend data's isCourseComplete is not set to true.

SCORM.data.get(cmi.suspend_data)  value: {"spoor":{"completion":"111111111111111111111","_isCourseComplete":false,"_isAssessmentPassed":false}}

But the LMSSetValue('cmi.core.lesson_status', 'completed') is set correctly.

**Comment by moloko** [comment]
What are your spoor settings in config.json? 



—
Matt Leathes

**Comment by aniketdharia** [comment]
"_spoor": {
        "_isEnabled": true,
        "_tracking": {
            "_requireCourseCompleted": true,
            "_requireAssessmentPassed": false,
            "_shouldSubmitScore": false
        }

**Comment by moloko** [comment]
And has it always been set to that? The reason I ask is that if you originally had both ```_requireCourseCompleted``` and ```_requireAssessmentPassed``` set to false, there was a bug (which I've just fixed) that meant the course would still mark as completed if you either completed all blocks or completed the assessment.
Otherwise I can't think of anything. Can you replicate this with a completely fresh attempt (i.e. no chance of old tracking data confusing matters)?

**Comment by moloko** [comment]
can this be closed now?

**Comment by aniketdharia** [comment]
Yes!
